# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-17 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0002_redirect_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
