# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-17 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0003_redirect_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redirect',
            old_name='count',
            new_name='visit_count',
        ),
    ]
